### ISSUE TITLE
Cancel does not remvoe batch tool from list of processes

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.InstallationValidator#11]
There is a handle somewhere that is not freed as the tool PKSim.BatchTool.exe is  still visible in process explorer

**Comment by rwmcintosh** [comment]
I cannot reproduce it.
Did you reproduce that? You said you were going to, but I did not hear back.

**Comment by msevestre** [comment]
could not reproduce also. Let's assume this is fixed
