### ISSUE TITLE
Create reporting infrastructure

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/OSPSuite.InstallationValidator#22]
This is about making it possible to get a basic empty report.

Structure of the report is not clear at this time.

**Comment by msevestre** [comment]
* Date/Time
* Computer name (MAC)
* Operating system
* Version numbers of PK-Sim and MoBi (incl build number)
* Location of input folder
* Location of installed output folder 
* Location of calculated output folder 
* _**Default**_ Absolute/relative solver tolerances used for calculation (= _tolerances used for calculation if not explicitly defined in the input file_
* Overall validation result: OK or FAILED
* In case of failure:
  * For every pair of output files with failed comparison:
    * For every curve with failed comparison: max. deviation and threshold used
    * charts with curves showing differences (log and lin)

**Comment by msevestre** [comment]
Suggestion is to add Absolute and Relative tolerance to the report of each failing simulations instead of a global value that does not exist. Only a default value is used but it may well be overwritten in json files simulating user behavior
