### ISSUE TITLE
Create UI

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/OSPSuite.InstallationValidator#3]
Includes getting the IoC infrastructure working

The default UI will be DevExpress components for
- a text box for showing ongoing results
- textbox for inputs folder
- textbox for outputs folder
- textbox for log file location

**Comment by msevestre** [comment]
No input or log file location required

**Comment by msevestre** [comment]
No input or log file location require:
* Input will be derived from PK-Sim Install (or InstallationValidator Install)
* Log file will be dumped in the output folder
